import {
    generatePlaceValueLarge,
    generateExpandedForm,
    generateCompareLarge,
    generateAdditionLarge,
    generateSubtractionLarge,
    generateMultiplicationLarge,
    generateDivisionLarge,
    generateEstimationOps,
    generateEquivalentFractions,
    generateSimplifyFractions,
    generateAddUnlikeFractions,
    generateMixedImproper,
    generateDecimalPlaceValue,
    generateDecimalOps,
    generateUnitConversion,
    generateTimeElapsed,
    generateAngleTypes,
    generateAreaPerimeterShapes,
    generatePieChart,
    generateFactors,
    generateLCM,
    generateHCF,
    generateFactorTree,
    generateSymmetry,
    generateNumberPattern,
    generatePicturePattern
} from './grade5Generators.mjs';

const generate = (generator, count = 10) => {
    return Array.from({ length: count }, () => generator());
};

const Grade5Questions = {
    q1: generate(generatePlaceValueLarge),
    q2: generate(generateCompareLarge),
    q3: generate(generateExpandedForm),
    q4: generate(generateAdditionLarge),
    q5: generate(generateSubtractionLarge),
    q6: generate(generateMultiplicationLarge),
    q7: generate(generateDivisionLarge),
    q8: generate(generateEstimationOps),
    q9: generate(generateEquivalentFractions),
    q10: generate(generateSimplifyFractions),
    q11: generate(generateAddUnlikeFractions),
    // q12: generate(generateMixedImproper),
    q12: generate(generateDecimalPlaceValue),
    q13: generate(generateDecimalOps),
    q14: generate(generateUnitConversion),
    q15: generate(generateTimeElapsed),
    q16: generate(generateAngleTypes),
    q17: generate(generateAreaPerimeterShapes),
    q18: generate(generatePieChart),
    q19: generate(generateFactors),
    q20: generate(generateLCM),
    q21: generate(generateFactorTree),
    q22: generate(generateSymmetry),
    q23: generate(generateNumberPattern),
    q24: generate(generatePicturePattern),
    // q25: generate(generateEquivalentFractions),
    // q24: generate(generateMultiplicationLarge),
    // q25: generate(generateEquivalentFractions),
    // q26: generate(generateDecimalOps),
    // q27: generate(generateUnitConversion),
    // q28: generate(generateAreaPerimeterShapes),
    // q29: generate(generateFactors),
    // q30: generate(generateHCF)
};

export default Grade5Questions;
