import {
    generateAddition2digit,
    generateAddition3digit,
    generateSubtraction2digit,
    generateSubtraction3digit,
    generateMultiplication7and8and9and12,
    generateMultiplication13to19,
    generateDivision1stlevel,
    generateDivision2ndlevel,
    generateMissingNumberAddition,
    generateMissingNumberSubtraction,
    generateAdditionThenSubtraction,
    generateSubtractionThenAddition,
    generateFractions,
    generateCompareFractions,
    generateNumberToWords,
    generateWordsToNumber,
    generateShapes,
    generateDoublingQuestion,
    generateHalvingQuestion,
    generateSymmetry,
    generateLengthConversion,
    generateWeightConversion,
    generateCapacityConversion,
    generateTimeReading,
    generateIdentifyMoney,
    generateMoneyOperations,
    generateTally,
    generateNumberPattern
} from './grade3Generators.mjs';

const generate = (generator, count = 10) => {
    return Array.from({ length: count }, () => generator());
};

const Grade3Questions = {
    q1: generate(generateAddition2digit),
    q2: generate(generateAddition3digit),
    q3: generate(generateSubtraction2digit),
    q4: generate(generateSubtraction3digit),
    q5: generate(generateMultiplication7and8and9and12),
    q6: generate(generateMultiplication13to19),
    q7: generate(generateDivision1stlevel),
    q8: generate(generateDivision2ndlevel),
    q9: generate(generateMissingNumberAddition),
    q10: generate(generateMissingNumberSubtraction),
    q11: generate(generateAdditionThenSubtraction),
    q12: generate(generateSubtractionThenAddition),
    // q13: generate(generateFractions),
    q13: generate(generateFractions),
    // q15: generate(generateCompareFractions),
    q14: generate(generateNumberToWords),
    q15: generate(generateWordsToNumber),
    // q16: generate(generateShapes),
    q16: generate(generateDoublingQuestion),
    q17: generate(generateHalvingQuestion),
    q18: generate(generateSymmetry),
    q19: generate(generateLengthConversion),
    q20: generate(generateWeightConversion),
    q21: generate(generateCapacityConversion),
    q22: generate(generateTimeReading),
    q23: generate(generateIdentifyMoney),
    q24: generate(generateMoneyOperations),
    q25: generate(generateTally),
    q26: generate(generateNumberPattern),

    // Fill remaining slots with mixed topics if needed or reuse existing
    // q19: generate(generateAddition),
    // q20: generate(generateSubtraction),
    // q21: generate(generateMultiplication),
    // q22: generate(generateDivision),
    // q23: generate(generateMissingNumber),
    // q24: generate(generateMixedOperations),
    // q25: generate(generateFractions),
    // q26: generate(generateCompareFractions),
    // q27: generate(generateShapes),
    // q28: generate(generateSymmetry),
    // q29: generate(generateLengthConversion),
    // q30: generate(generateWeightConversion)
};

export default Grade3Questions;