import {
    generateNaturalWholeNumbers,
    generateIntegers,
    generateFractions,
    generateDecimals,
    generateLCM,
    generateHCF,
    generateRatioProportion,
    generateSquareRoots,
    generateCubeRoots,
    generateExponentsNegative,
    generateBODMAS,
    generateAlgebraicAdditionSubtraction,
    generateAlgebraicMultiplication,
    generateAlgebraicDivision,
    generateLinearEquationOneVar,
    generateSimultaneousEquations,
    generateQuadraticEquation,
    generatePerimeter,
    generateArea,
    generateCartesianPoint,
    generateCoordinateGeometry,
    generateSectionFormula,
    generateTrigonometry,
    generateTrigRatios,
    generatePythagoras,
    generateClocks,
    generateProbability,
    generateDiceProbability,
    generateAgeProblem,
    generateNumberSquareProblem
} from './grade10Generators.mjs';

const generate = (generator, count = 10) => {
    // Generator wrapper
    return Array.from({ length: count }, () => generator());
};

const Grade10Questions = {
    q1: generate(generateNaturalWholeNumbers),
    q2: generate(generateIntegers),
    q3: generate(generateFractions),
    q4: generate(generateDecimals),
    q5: generate(generateLCM),
    q6: generate(generateHCF),
    q7: generate(generateRatioProportion),
    q8: generate(generateSquareRoots),
    q9: generate(generateCubeRoots),
    q10: generate(generateExponentsNegative),
    q11: generate(generateBODMAS),
    q12: generate(generateAlgebraicAdditionSubtraction),
    q13: generate(generateAlgebraicMultiplication),
    q14: generate(generateAlgebraicDivision),
    q15: generate(generateLinearEquationOneVar),
    q16: generate(generateSimultaneousEquations),
    q17: generate(generateQuadraticEquation),
    q18: generate(generatePerimeter),
    q19: generate(generateArea),
    q20: generate(generateCartesianPoint),
    q21: generate(generateCoordinateGeometry),
    q22: generate(generateSectionFormula),
    q23: generate(generateTrigonometry),
    q24: generate(generateTrigRatios),
    q25: generate(generatePythagoras),
    q26: generate(generateClocks),
    q27: generate(generateProbability),
    q28: generate(generateDiceProbability),
    q29: generate(generateAgeProblem),
    q30: generate(generateNumberSquareProblem)
};


export const Grade10GeneratorMap = {
    "Number Sense / Natural & Whole": generateNaturalWholeNumbers,
    "Number Sense / Integers": generateIntegers,
    "Number Sense / Fractions": generateFractions,
    "Number Sense / Decimals": generateDecimals,
    "Number Sense / LCM": generateLCM,
    "Number Sense / HCF": generateHCF,
    "Arithmetic / Ratio & Proportion": generateRatioProportion,
    "Arithmetic / Clocks": generateClocks,
    "Number Sense / Square Roots": generateSquareRoots,
    "Number Sense / Cube Roots": generateCubeRoots,
    "Number Sense / Exponents": generateExponentsNegative,
    "Arithmetic / BODMAS": generateBODMAS,
    "Algebra / Addition & Subtraction": generateAlgebraicAdditionSubtraction,
    "Algebra / Multiplication": generateAlgebraicMultiplication,
    "Algebra / Division": generateAlgebraicDivision,
    "Algebra / Linear Equations": generateLinearEquationOneVar,
    "Algebra / Simultaneous Equations": generateSimultaneousEquations,
    "Algebra / Quadratic Equations": generateQuadraticEquation,
    "Algebra / Word Problems (Age)": generateAgeProblem,
    "Algebra / Word Problems (Quadratic)": generateNumberSquareProblem,
    "Mensuration / Perimeter": generatePerimeter,
    "Mensuration / Area": generateArea,
    "Coordinate Geometry / Quadrants": generateCartesianPoint,
    "Coordinate Geometry / Distance Formula": generateCoordinateGeometry,
    "Coordinate Geometry / Section Formula": generateSectionFormula,
    "Trigonometry / Ratios": generateTrigonometry,
    "Trigonometry / Standard Angles": generateTrigRatios,
    "Geometry / Pythagoras Theorem": generatePythagoras,
    "Probability / True/False": generateProbability,
    "Probability / Dice": generateDiceProbability
};

export default Grade10Questions;

